cart/urls.py
# cart/urls.py

from django.urls import path

from .views import *

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", cart_add, name="cart_add"),
    path("remove/<int:product_id>/", cart_remove, name="cart_remove"),
    
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),

    path("orders/", include("orders.urls", namespace="orders")),
 
    path("payment/", include("payment.urls", namespace="payment")),
       
    path("coupons/", include('coupons.urls', namespace='coupons')),
   
    path("", include("shop.urls", namespace="shop")),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    

shop/urls.py
# shop/urls.py

from django.urls import path

from .views import product_detail, product_list

app_name = "shop"

urlpatterns = [
    path("", product_list, name="product_list"),
    path(
        "<slug:category_slug>/",
        product_list,
        name="product_list_by_category",
    ),
    path(
        "<int:id>/<slug:slug>/",
        product_detail,
        name="product_detail",
    ),
    
]

shop/models.py
# shop/models.py

from django.db import models
from django.urls import reverse


class Category(models.Model):
    
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
            
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    
    def __str__(self):
        return self.name

    
    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])
    
        
    
class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE,
    )
    
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(
        upload_to='products/%Y/%m/%d',
        blank=True,
        
    )
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['name', ]
        indexes = [
            models.Index(fields=['id', 'slug', ]),
            models.Index(fields=['name', ]),
            models.Index(fields=['-created', ]),
            
        ]
        
    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug,])
    
    

shop/views.py
# shop/views.py

from django.shortcuts import get_object_or_404, render
from .models import Product, Category
from cart.views import CartAddProductForm

from .recommender import Recommender

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    
    return render(
        request,
        "shop/product/list.html",
        {
            "category": category,
            "categories": categories,
            "products": products,
        }
    )
    
def product_detail(request, id, slug):
    product = get_object_or_404(
        Product, id=id, slug=slug, available=True,
    )
    cart_product_form = CartAddProductForm()
    
    # show recommendations
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)
    
    
    return render(
        request,
        "shop/product/detail.html",
        {"product": product, "cart_product_form": cart_product_form,'recommended_products': recommended_products},
    )
    

shop/templates/shop/base.html
<!-- shop/templates/shop/base.html -->
 {% load static %}

 <!DOCTYPE html>
 <html>
    <head>
        <meta charset="utf-8"/>
        <title>{% block title %}My shop{% endblock %}</title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="header">
            <a href="/" class="logo">My shop</a>
        </div>
        <div id="subheader">
            <div class="cart">
                {% with tota_items=cart|length %}
                    {% if tota_items > 0 %}
                        Your cart:
                        <a href="{% url "cart:cart_detail" %}">
                            {{ tota_items }} item{{total_items|pluralize}},
                            ${{cart.get_total_price}}
                        </a>
                    {% elif not order %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </div>
        </div>
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>